[changelog]
header = """
# Changelog\n
All notable changes to this project will be documented in this file. See [conventional commits](https://www.conventionalcommits.org/) for commit guidelines.\n
"""

body = """
{% if version %}\
    ## [{{ version | trim_start_matches(pat="v") }}] - {{ timestamp | date(format="%Y-%m-%d") }}
{% endif %}\
{% for group, commits in commits | group_by(attribute="group") %}
    ### {{ group | upper_first }}
    {% for commit in commits | filter(attribute="scope") | sort(attribute="scope") %}
        - **({{commit.scope}})**{% if commit.breaking %} [**breaking**]{% endif %} \
            {{ commit.message }} - ([{{ commit.id | truncate(length=7, end="") }}]($REPO/commit/{{ commit.id }}))
    {% endfor %}
    {% raw %}\n{% endraw %}\
    {%- for commit in commits %}
        {%- if commit.scope -%}
        {% else -%}
            - {% if commit.breaking %} [**breaking**]{% endif %} \
                {{ commit.message }} - ([{{ commit.id | truncate(length=7, end="") }}]($REPO/commit/{{ commit.id }}))
        {% endif -%}
    {% endfor -%}
{% endfor %}\n
{% if version %}
    {% if previous.version %}
      **Full Changelog**: [{{ previous.version }}...{{ version }}]($REPO/compare/v{{ previous.version }}...v{{ version }})
    {% endif %}
{% else -%}
  {% raw %}\n{% endraw %}
{% endif %}
"""

# remove the leading and trailing whitespace from the template
trim = true

postprocessors = [
    { pattern = '\$REPO', replace = "https://github.com/beeb/swpui" },
]

[git]
# parse the commits based on https://www.conventionalcommits.org
conventional_commits = true
# filter out the commits that are not conventional
filter_unconventional = true
# process each line of a commit as an individual commit
split_commits = false

commit_parsers = [
    { body = ".*security", group = "Security" },
    { message = "^chore: release", skip = true },
    { message = "^doc", group = "Documentation" },
    { message = "^fix", group = "Fixed" },
    { message = "^test", group = "Tests" },
    { message = "^feat", group = "Added" },
    { message = "^.*: add", group = "Added" },
    { message = "^.*: support", group = "Added" },
    { message = "^.*: remove", group = "Removed" },
    { message = "^.*: delete", group = "Removed" },
    { message = "^.*: fix", group = "Fixed" },
    { message = "^.*", group = "Changed" },
] # regex for parsing and grouping commits

# protect breaking changes from being skipped due to matching a skipping commit_parser
protect_breaking_commits = true
# filter out the commits that are not matched by commit parsers
filter_commits = false
# glob pattern for matching git tags
tag_pattern = "v[0-9]*"
# sort the tags topologically
topo_order = false
# sort the commits inside sections by oldest/newest order
sort_commits = "oldest"
